# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ai-trascripts-analyzer-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies and build
        env:
          NEXT_PUBLIC_API_URL: "https://ai-transcripts-analyzer-backend.azurewebsites.net"
          NODE_ENV: production
        run: |
          npm ci
          npm run build

      - name: Archive production build
        run: |
          # Use the complete standalone directory as is
          cd .next/standalone && zip -r ../../build.zip .
        shell: bash

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip build.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EC6107F76F384DF8B6C5F43913E370E9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D0F93D12DD3D451FBFBCA5175EA9B03E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5CEB93400DE04E75AA8F29910C6C868C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ai-trascripts-analyzer-frontend"
          slot-name: "Production"
          package: .
